UltraStar-Deluxe/Play

- CONTRIBUTING.md
fixes a typo in the contributing.md
> fixed typo in contributing.md

- UltraStar Play/Assets/Editor/ManagersTests.cs
- UltraStar Play/Assets/src/model/song/SongParser.cs
- UltraStar Play/Assets/src/view/base/SLoadingController.cs
It fixes some compile issues. The testcase will probably fail but I just have no idea what it is supposed to test anyway (if I were to test ClearPlayers, I'd expect it to assert that GetPlayers returns an empty list or something (which also implicitly checks for it being an actual object) but maybe it has some historic value, so I've not touched that for right now)
I am on 2018.2.0f2 (instead of 2018.1.4f1) but I think that's not a big deal?
> fix some compilation issues

- UltraStar Play/Assets/Common/Model/Song/Builder/VoicesBuilder.cs
- UltraStar Play/Assets/Common/Model/Song/Sentence/Note/Note.cs
- UltraStar Play/Assets/Common/Model/Song/Sentence/Sentence.cs
- UltraStar Play/Assets/Scenes/About/AboutScene.unity
- UltraStar Play/Assets/Scenes/Loading/LoadingScene.unity
- UltraStar Play/Assets/Scenes/Sing/PlayerController/PlayerUiController/SentenceDisplayer.cs
This PR adds basic support for usdx song files with negative syllable timings. Such files usually exist because of improper use of the GAP tag. 
UltraStar Deluxe, Vocaluxe and Performous support usdx song files with negative integer values for syllable timing. UltraStar Play should support this as well.
> Support negative syllable timing

- .travis.yml
- tools/travis/activat.ion
fixes travis-ci automated build and test
#1
> fix travis build

- .travis.yml
enable build artifacts upload in .travis.yml
#1 
Please do not merge this yet.
> enable build artifacts upload in .travis.yml

- README.md
Added links to the repo's of UltraStar Deluxe, Performous and Vocaluxe as they're mentioned here within this readme.
Adds links to the various github projects of other karaoke programs.
None
I thought it'd be nice to also support other open source projects as they are mentioned here without a link.
None.
> Readme: Linking othere karaoke programs

- UltraStar Play/Assets/Scenes/Sing/SingSceneController.cs
Fix issues with stuttering video playback.
None
> smooth synchronization of video playback by adjusting the playback speed

- UltraStar Play/Assets/Common/Audio/Recording/CamdAudioSamplesAnalyzer.cs
- UltraStar Play/Assets/Common/Audio/Recording/IAudioSamplesAnalyzer.cs
- UltraStar Play/Assets/Common/Audio/Recording/MicrophonePitchTracker.cs
- UltraStar Play/Assets/Common/Model/Microphone/MicProfile.cs
- UltraStar Play/Assets/Scenes/Demos/MicrophoneDemo/MicrophoneDemoSceneController.cs
- UltraStar Play/Assets/Scenes/Options/RecordingOptions/RecordingOptionsMicVisualizer.cs
- UltraStar Play/Assets/Scenes/Sing/PlayerController/PlayerNoteRecorder.cs
- UltraStar Play/Assets/Scenes/SongSelect/MicList/SongSelectMicListEntry.cs
- Implemented microphone input amplification
- used threshold and amplification from MicProfile
- AudioSampleAnalyzer improvements
- AudioSampleAnalyzer throws new PitchEvent(0) in all cases when there was a samples frame, but no pitch was detected
> minor microphone input improvements

- UltraStar Play/Assets/Scenes/Sing/PlayerController/PlayerScoreController.cs
- UltraStar Play/Assets/Scenes/SingingResults/SingingResultsSceneKeyboardController.cs
- UltraStar Play/Assets/Scenes/SongSelect/SongRoulette/SongRouletteController.cs
- UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneController.cs
- UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneKeyboardInputController.cs
- shortcut R in SongSelectionScene to select a random song
- backspace key closes the SingRecultScene
- devision by zero fix for songs without golden notes or for song with only non-normal notes (freestyle/...)
> random song selection & devision by zero fix

- .travis.yml
- UltraStar Play/Assets/Editor/BuildCommand.cs
- tools/download-dependencies/download-fullserializer.sh
- tools/download-dependencies/download-leantween.sh
- tools/download-dependencies/download-nlayer.sh
- tools/download-dependencies/download-unirx.sh
Enables build-targets mac and linux in .travis.yml .
#1 
Improve test coverage.
> enable build-targets mac and linux in .travis.yml

- .travis.yml
- tools/travis/docker_build.sh
Cleans up travis-ci output by adding a travis-ci fold according to https://garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
Improve readability of travis-ci build log.
> clean up travisci output log

- UltraStar Play/Assets/Common/UI/CursorUiText.prefab
- UltraStar Play/Assets/Common/Util/CanvasUtils.cs
- UltraStar Play/Assets/Scenes/About/AboutScene.unity
- UltraStar Play/Assets/Scenes/Credits/CreditsScene.unity
- UltraStar Play/Assets/Scenes/Demos/DependencyInjectionDemo/DependencyInjectionDemoScene.unity
- UltraStar Play/Assets/Scenes/Demos/I18NDemo/I18NDemoScene.unity
- UltraStar Play/Assets/Scenes/Demos/MicrophoneDemo/MicrophoneDemoScene.unity
- UltraStar Play/Assets/Scenes/Demos/ThemeDemo/ThemeDemoScene.unity
- UltraStar Play/Assets/Scenes/Loading/LoadingScene.unity
- UltraStar Play/Assets/Scenes/Main/MainScene.unity
- UltraStar Play/Assets/Scenes/Options/GameOptions/OptionsGameScene.unity
- UltraStar Play/Assets/Scenes/Options/GraphicOptions/OptionsGraphicsScene.unity
- UltraStar Play/Assets/Scenes/Options/OptionsScene.unity
- UltraStar Play/Assets/Scenes/Options/PlayerProfileSetup/PlayerProfileSetupScene.unity
- UltraStar Play/Assets/Scenes/Options/RecordingOptions/RecordingOptionsScene.unity
- UltraStar Play/Assets/Scenes/Options/SoundOptions/OptionsSoundScene.unity
- UltraStar Play/Assets/Scenes/Sing/SingSceneController.cs
- UltraStar Play/Assets/Scenes/SingingResults/SingingResultsScene.unity
- UltraStar Play/Assets/Scenes/SongSelect/SongSelectScene.unity
fixes missing canvas tags, fixes default song not being found, improves canvas not found exception message.
> fix gameplay

- UltraStar Play/Assets/Common/Util/Extensions/ImageExtensions.cs
- UltraStar Play/Assets/Common/Util/NumberUtils.cs
- UltraStar Play/Assets/Common/Util/NumberUtils.cs.meta
- UltraStar Play/Assets/Scenes/Options/RecordingOptions/AmplificationSlider.cs
- UltraStar Play/Assets/Scenes/Options/RecordingOptions/RecordingOptionsMicVisualizer.cs
- recording options mic visualization considers noise suppression and amplification
- mini refactoring of generic Limit method in NumberUtils
#92
> RecordingOptions: visualize noise suppression and amplification

- UltraStar Play/Assets/Common/Scene/IDefaultSceneDataProvider.cs
- UltraStar Play/Assets/Common/Scene/IDefaultSceneDataProvider.cs.meta
- UltraStar Play/Assets/Common/Scene/SceneDataException.cs
- UltraStar Play/Assets/Common/Scene/SceneDataException.cs.meta
- UltraStar Play/Assets/Common/Scene/SceneNavigator.cs
- UltraStar Play/Assets/Common/Util/GameObjectUtils.cs
- UltraStar Play/Assets/Scenes/Sing/DefaultSingSceneDataProvider.cs
- UltraStar Play/Assets/Scenes/Sing/DefaultSingSceneDataProvider.cs.meta
- UltraStar Play/Assets/Scenes/Sing/SingScene.unity
- UltraStar Play/Assets/Scenes/Sing/SingSceneController.cs
- UltraStar Play/Assets/Scenes/SingingResults/DefaultSingingResultsSceneDataProvider.cs
- UltraStar Play/Assets/Scenes/SingingResults/DefaultSingingResultsSceneDataProvider.cs.meta
- UltraStar Play/Assets/Scenes/SingingResults/SingingResultsScene.unity
- UltraStar Play/Assets/Scenes/SingingResults/SingingResultsSceneController.cs
- UltraStar Play/Assets/Scenes/SongEditor/DefaultSongEditorSceneDataProvider.cs
- UltraStar Play/Assets/Scenes/SongEditor/DefaultSongEditorSceneDataProvider.cs.meta
- UltraStar Play/Assets/Scenes/SongEditor/SongEditorScene.unity
- UltraStar Play/Assets/Scenes/SongEditor/SongEditorSceneController.cs
Refactor the creation of default SceneData objects as proposed in #138.
This separates the only-for-development code a bit more from the normal code.
I welcome your feedback.
> refactored creation of default scene data into provider classes

- tools/download-dependencies/download-nlayer.sh
Update NLayer dependency to include nullpointer bugfix for reusing already played audio file handle.
fixes #133
> Update NLayer dependency

- .travis.yml
Also upload builds for linux and macOS target
This makes it easier for more people to test development versions.
> also upload builds for linux and macOS target

- UltraStar Play/Assets/Common/Video/SongVideoPlayer/SongVideoPlayer.cs
- UltraStar Play/Assets/Common/Video/SongVideoPlayer/SongVideoPlayer.prefab
- UltraStar Play/Assets/Scenes/Sing/SingSceneVideoMaterial.mat
- UltraStar Play/Assets/Scenes/SongEditor/SongEditorVideoMaterial.mat
- UltraStar Play/Assets/Scenes/SongSelect/Preview/SongPreviewController.cs
- UltraStar Play/Assets/Scenes/SongSelect/Preview/SongSelectVideoMaterial.mat
- UltraStar Play/Assets/Scenes/SongSelect/Preview/SongSelectVideoRenderTexture.renderTexture
- UltraStar Play/Assets/Scenes/SongSelect/SongSelectScene.unity
- video materials now use shader "UI/Unlit/Transparent" to fix render issues
- video preview has a transparency fade-in effect. This does not start before the video has been loaded and a frame can be shown
- SongSelect: fixed aspect ratio issues of video preview
#155 
#157
> Fix video issues

- UltraStar Play/Assets/Common/Input.meta
- UltraStar Play/Assets/Common/Input/GlobalKeyboardShortcutManager.cs
- UltraStar Play/Assets/Common/Input/GlobalKeyboardShortcutManager.cs.meta
- UltraStar Play/Assets/Common/Scene/CommonSceneObjects.prefab
- UltraStar Play/Assets/Scenes/Options/GraphicOptions/FullscreenSlider.cs
Toggle full-screen via F11.
#161
> added GlobalKeyboardShortcutManager to toggle full-screen mode

- UltraStar Play/ProjectSettings/ProjectSettings.asset
Fix iOS Player Settings that were mentioned on Gitter.
- added microphoneUsageDescription
- checked "mute other audio sources" to enable Bluetooth microphones
> fix iOS Player Settings

- .travis.yml
Try different docker image for android build.
I did not change the Unity license content. Still, with a bit of luck this could work.
> travis: try different docker image for android build

- documentation/assembly-dependencies.plantuml
See title.
I forgot to do this in #216.
- also added [documentation on logging](https://github.com/UltraStar-Deluxe/Play/wiki/Logging-(Serilog)) in the wiki
> added Serilog to assembly-dependencies.plantuml

- UltraStar Play/Assets/Scenes/SongEditor/Controls/SongMetaTags/Bpm/CountBpmButton.cs
- UltraStar Play/Assets/Scenes/SongEditor/Controls/SongMetaTags/Bpm/CountBpmButton.cs.meta
- UltraStar Play/Assets/Scenes/SongEditor/SongEditorScene.unity
Tiny PR that implements #208 
- in SongEditor, next to the BPM settings, there is a new button that counts BPM when clicked
close #208
> SongEditor: added button to find BPM

- UltraStar Play/Assets/Common/Model/SongMetaManager.cs
- UltraStar Play/Assets/Scenes/Options/ContentOptions/ContentDownloadSceneController.cs
> rescan songs if song folders changed or new songs have been downloaded

- UltraStar Play/Assets/Common/UI/DynamicallyCreatedImage/SimpleUnlitTexturedTransparentShader.shader
- UltraStar Play/Assets/Resources/Translations/messages_pl.properties
- UltraStar Play/Assets/Resources/Translations/messages_pl.properties.meta
- UltraStar Play/Assets/Scenes/Main/MainSceneUiControl.cs
- Fixes shader issue with UI mask in Viewport (visible only when you scroll to the top): ![rawimg](https://user-images.githubusercontent.com/37487149/135732001-5173267b-b9ba-48c5-ab1f-498486886f58.png)
- Adds the Polish language as messages_pl.properties file.
- Implements language translation on every button in the Main scene (the Jukebox and Party ones weren't localized).
> Add Polish language as properties file, initialize all translations in Main Menu, fix UI shader by adding mask

- UltraStar Play/Assets/Resources/Translations/messages_fr.properties
- UltraStar Play/Assets/Resources/Translations/messages_fr.properties.meta
This PR add french translation to the game
none
Contribute to the project and spread it in french speaking countries
> add french translation

- UltraStar Play/Assets/Scenes/Loading/LoadingSceneControl.cs
- UltraStar Play/Assets/Scenes/Scenes.asmdef
- UltraStar Play/Assets/VERSION.txt
- UltraStar Play/Packages/manifest.json
- UltraStar Play/Packages/packages-lock.json
See title.
Therefor, I added a lib to check and ask for any permissions on Android: https://github.com/yasirkula/UnityAndroidRuntimePermissions
In contrast, the Unity API is cumbersome.
close  #301
See #301 "Only after restarting the app mics were found".
I did not have this issue anymore when the permission is granted at startup.
> ask for microphone permission in loading scene (Android)

- UltraStar Play/Packages/playshared/Runtime/Resources/Translations/messages_es.properties
- UltraStar Play/Packages/playshared/Runtime/Resources/Translations/messages_es.properties.meta
Added spanish translation. NOTE: This is not tested since I never used before Unity and I can't compile the project for some reason :/
None I think.
Adding spanish translation.
As I said, this is not tested since I never used before Unity and I can't compile the project for some reason. I duplicated english properties and then translated. I readed the documentation to see how to properly translate it but since I don't have any experience I'm not sure if I did it well.
> Added spanish translation

- UltraStar Play/Assets/Scenes/SongEditor/NoteArea/Drag/NoteAreaSelectionDragListener.cs
- UltraStar Play/Assets/Scenes/SongEditor/SongEditorSceneInputControl.cs
Fix: mouse select scroll horizontal direction in song editor changed to expected direction
Changed: mouse scroll wheel vertical direction changed to the same as in song selection (UP -> scroll left, DOWN -> scroll right)
#364
> song editor scrolls the wrong way

- UltraStar Play/ProjectSettings/ProjectSettings.asset
Unlick the project from Unity Cloud.
None.
We don't use Unity Cloud.
None.
None.
> Removed the connection to Unity Cloud

- UltraStar Play/ProjectSettings/ProjectSettings.asset
Add Input System settings to preloaded assets.
None.
Unity wants it.
None.
None.
> Add Input System settings to preloaded assets

- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/aac.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/aiff.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/avi.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/f4v.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/flac-mkv.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/flac-webm-vp8.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/flac.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/flv.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/m4a.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/m4v.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/midi.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/mkv.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/mov.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/mp3-ConstantBitRate.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/mp3-VariableBitRate.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/mp4-av1.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/mp4-hvec.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/mp4.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/mpeg2.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/ogg-mkv.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/ogg-webm-vp8.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/ogg.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/wav.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/webm-vp8.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/webm-vp9.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/wma.txt
- UltraStar Play/Assets/PlayModeTests/MediaFileFormatTests/MediaFileFormatTestSongs/wmv.txt
Renames all the test songs from TestTitle to a title that describes the audio and/or video format support being tested by that song.
None.
Makes it easier to test the game.
None.
The test song folder should be auto-added to the library when playing in editor. That's another pull request.
> Make the test song names distinguishable

- UltraStar Play/Assets/StreamingAssets/Themes/vinyl-with-transparent-lyrics.json.meta
Fix vinyl with transparent lyrics json meta file.
None.
Broken assets bad.
None.
None.
> Fix vinyl with transparent lyrics json meta file

- UltraStar Play/Assets/Background Bokeh VFX.meta
- UltraStar Play/Assets/CartoonVFX9X.meta
- UltraStar Play/Assets/Common/Vfx/VfxPrefabs/BackgroundLightPrefabs.meta
- UltraStar Play/Assets/Confetti FX Pro.meta
- UltraStar Play/Assets/Hovl Studio.meta
- UltraStar Play/Assets/StreamingAssets/Mods/CoverAndBackgroundImageFromFolder/bin.meta
- UltraStar Play/Assets/StreamingAssets/Mods/CoverAndBackgroundImageFromFolder/obj.meta
- UltraStar Play/Assets/StreamingAssets/Mods/JukeboxAndSing/bin.meta
- UltraStar Play/Assets/StreamingAssets/Mods/JukeboxAndSing/obj.meta
- UltraStar Play/Assets/StreamingAssets/Mods/LocalFolderSongRepository/bin.meta
- UltraStar Play/Assets/StreamingAssets/Mods/LocalFolderSongRepository/obj.meta
- UltraStar Play/Assets/StreamingAssets/Mods/UltraStarDeluxeHighscoreConnector/bin.meta
- UltraStar Play/Assets/StreamingAssets/Mods/UltraStarDeluxeHighscoreConnector/obj.meta
Delete empty folders.
None.
Tidy.
None.
None.
> Delete empty folders
