UltraStar-Deluxe/Play

UltraStar Play/Assets/src/model/song/SongParser.cs

As it says on the tin. Rap = R and RapGolden = G, taken from this comment: https://github.com/UltraStar-Deluxe/Play/pull/26#issuecomment-429874943
I moved the "what note type is this symbol" logic to a separate function with a switch because the if/else was getting out of hand.

Add support for reading Rap and RapGolden notes from txt files

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Dev_discussion.md
.github/ISSUE_TEMPLATE/Feature_request.md

- Simplified the issue templates for bug reports and feature requests
- Added issue template for development discussions
Improve readability and streamline the issue templates based on previous project experiences with UltraStar Deluxe, Stepmania and similar.
Allow for development discussions using the github projects' issue features.

Simplify issue templates

---

UltraStar Play/Assets/Scenes/Sing/SingScene.unity
UltraStar Play/Assets/Scenes/Sing/SingSceneController.cs

It replace the usage of the NAudio library with native Unity functionality, so the game runs on non Windows systems ie. Linux.
NAudio uses Windows exclusive APIs, so moving away from it at some point is inevitable.
The NAudio library is still found under `Assets/NAudio`, but could be removed without breaking anything.

Replace NAudio usage with native Unity functions

---

UltraStar Play/Assets/Common/Audio/Recording/CamdAudioSamplesAnalyzer.cs
UltraStar Play/Assets/Scenes/Sing/SingScene.unity
UltraStar Play/Assets/Scenes/Sing/SingSceneController.cs
UltraStar Play/Assets/Scenes/Sing/TimeBar/TimeBarTimeLine.cs

Fix some issues.
Conversion of duration-in-millis to duration-in-seconds was using multiply instead of division.
Furthermore, the duration of the song is not known directly at the start of the scene. The song is loaded first and afterwards the duration is known. Because of this, the init of the TimeBar had to be moved.

SingScene: fix issues with wrong calculation of song durations / positions

---

UltraStar Play/Assets/Scenes/Sing/SingSceneController.cs

Fixes the following issue that I introduces with my last PR: 
> Songs now sometimes quit early (for example when the last third of the song was just reached). They sometimes even quit while the gameplay was paused using spacebar key.

SingSceneController: fixed premature FinishScene

---

UltraStar Play/Assets/Common/Audio/Recording/CamdAudioSamplesAnalyzer.cs

- change the processing order to make the "halftone != -1" condition valid
- removed element wise division by "samplesSinceLastFrame" -> doesn't appear to be necessary for pitch detection
It could be worth considering to combine CircularAverageMagnitudeDifference() and CalculateBestFittingHalftone() into one method. This would make the correlation buffer obsolete. Granted the performance gain is not that huge, but in time critical applications moving data unnecessarily should be avoided.
I couldn't test any of the proposed changes. Please check beforehand if anything works as expected if you want to apply them.

small changes/fixes for pitch detection algo

---

UltraStar Play/Assets/Common/Audio/MidiUtils.cs
UltraStar Play/Assets/Common/Audio/Recording/CamdAudioSamplesAnalyzer.cs

Fix pitch detection parameters, namely frequencies and lowest singable note.
I found where the mysterious + 3 was coming from. The midi note of C2 (lowest singable voice) is 36 not 33.
Furthermore, there was an issue in the calculation of the frequencies. The octave offset was not correct.
You can find a good comparison of midi note, piano key, frequency, and note name (english and german) here: https://www.inspiredacoustics.com/en/MIDI_note_numbers_and_center_frequencies
I tested my changes with my guitar tuner and 440 Hz sine wave generated in Audacity. The pitch detection is correct now.

corrected pitch detection

---

UltraStar Play/Assets/Common/Util/InputUtils.cs
UltraStar Play/Assets/Plugins/UniInject/Injector.cs
UltraStar Play/Assets/Scenes/Sing/PlayerController/PlayerNoteRecorder.cs
UltraStar Play/Assets/Scenes/SongEditor/Actions/ExtendNotesAction.cs
UltraStar Play/Assets/Scenes/SongEditor/Actions/ExtendNotesAction.cs.meta
UltraStar Play/Assets/Scenes/SongEditor/Actions/MoveNotesAction.cs
UltraStar Play/Assets/Scenes/SongEditor/Actions/MoveNotesAction.cs.meta
UltraStar Play/Assets/Scenes/SongEditor/Actions/SongEditorActionBinder.cs
UltraStar Play/Assets/Scenes/SongEditor/Actions/ToggleNoteTypeAction.cs
UltraStar Play/Assets/Scenes/SongEditor/Actions/ToggleNoteTypeAction.cs.meta
UltraStar Play/Assets/Scenes/SongEditor/EditorNote/EditorNoteContextMenuHandler.cs
UltraStar Play/Assets/Scenes/SongEditor/EditorNote/EditorUiNote.cs
UltraStar Play/Assets/Scenes/SongEditor/Issues/EditorUiIssueDisplayer.cs
UltraStar Play/Assets/Scenes/SongEditor/NoteArea/NoteArea.cs
UltraStar Play/Assets/Scenes/SongEditor/SongEditorSceneKeyboardController.cs

- add keyboard shortcuts to make notes golden, freestyle, normal (by pressing G / F / N).
- make golden and freestyle notes visually more distinct by changing their font.
Also: refactoring of "move notes" and "extend notes" into proper song editor actions. This fixes undo/redo not working for these actions.
- I already updated the documentation.

song editor - make golden, freestyle, normal shortcuts

---

UltraStar Play/Assets/Common/Model/SettingsManager.cs
UltraStar Play/Assets/Common/Model/Song/SongMeta.cs
UltraStar Play/Assets/Common/Model/SongMetaManager.cs
UltraStar Play/Assets/Common/Model/StatsManager.cs
UltraStar Play/Assets/Scenes/Loading/LoadingSceneController.cs
UltraStar Play/Assets/Scenes/SongEditor/SongEditorSceneController.cs
UltraStar Play/Assets/Scenes/SongEditor/SongEditorSceneKeyboardController.cs

- store Settings.json and Database.json in Application.persistentDataPath (On many platforms, the folder which contains the executable is not writable)
- clean up / simplify some null checks in SongMeta.cs
- try catch scanning song folders, log exception and continue next folder
- keep mobile devices from turning off the screen while the game is running
- wait at least 2 seconds when the user presses a button in Loading Scene for game to load stuff
- support closing the SongEditor by pressing escape key
I tested UltraStar Play on my android phone and ran in a couple of issues. This PR fixes most of them.

improvements for mobile devices, fault tolerant song folder scanning

---

UltraStar Play/Assets/Scenes/SingingResults/SingingResultsSceneData.cs

Fixes the ArgumentException when there are multiple singing players with the same PlayerName and the SingResultScene was about to be shown.
````
ArgumentException: An item with the same key has already been added. Key: PlayerProfile
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <567df3e0919241ba98db88bec4c6696f>:0)
SingingResultsSceneData.AddPlayerScores (PlayerProfile profile, SingingResultsSceneData+PlayerScoreData scoreData) (at Assets/Scenes/SingingResults/SingingResultsSceneData.cs:17)
SingSceneController.FinishScene () (at …
```

fixed ending singing exception when multiple players have same name

---

UltraStar Play/Assets/Common/Audio/Recording/CamdAudioSamplesAnalyzer.cs

This is a tiny change.
Do not return history pitch if detection failed because the PlayerNoteRecorder will round to the target note when an unsingable note has been detected (#154), which is better for the player
I once added the "return history pitch" thing to have a more stable recording in the song editor. However, for the game it feels sluggish and is unfair when the pitch detection is not responding to player input

CamdAudioSamplesAnalyzer: do not return history pitch if detection failed

---

UltraStar Play/Assets/Common/Audio/AudioManager.cs
UltraStar Play/Assets/Common/Input/GlobalKeyboardShortcutManager.cs

- add shortcut to mute / unmute audio via F12 (global keyboard shortcut)
- the mute state is not persisted in the settings. It is intended to temporarily stop audio output.

mute / unmute audio via F12 (global keyboard shortcut)

---

UltraStar Play/Assets/Common/Util/File/FolderScanner.cs
UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneController.cs
UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneKeyboardInputController.cs

See title.
I also changed two lines to fix the issue reported on Gitter: search input field was still focused after it has been disabled.
see #149

FolderScanner: do not scan hidden folders (starting with dot)

---

UltraStar Play/Assets/Common/Audio/Recording/MicSampleRecorder.cs

On Linux (Debian Bullseye) an exception was thrown in the Recording setting:
"ArgumentException: Frequency of recording must be greater than zero (was: 0 Hz)".
This exception prevented the usage of any microphone in Ultrastar Play.
The issue was caused by misinterpreting the return value "maxFrequency" of the Unity function "GetDeviceCaps".
A value of zero indicates, that the device can handle any frequency. 
By passing this value directly to "UnityEngine.Microphone.Start()", the exception is generated.
Therefore a case distinction has to be made beforehand.

fixed microphone issue under linux

---

.travis.yml

Attempt to also build iOS and Android on Travis.
I found the docker images at https://hub.docker.com/r/gableroux/unity3d/tags
and the BuildTarget "iOS" and "Android" on https://docs.unity3d.com/ScriptReference/BuildTarget.html
So maybe this will just work.
close #189 
- documentation about CI has been updated

added travis config to build iOS and Android

---

.travis.yml

Remove Android build from travis.
The build is green, but did not generate anything and was running forever.
The log says: 
```
Android NDK was not installed with Unity at /opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
```
I think it might be this issue: https://gitlab.com/gableroux/unity3d/-/issues/85
At the end of the thread, it is said that newer docker images are available over here: https://hub.docker.com/r/unityci/editor/tags?page=1&name=2020.1.5
Maybe these do not have this issue.
However, it could be that these images require a new Unity license activation. And I am too lazy right now to repeat this procedure.
So conclusion: Android build failed. Remove it and see how iOS will do ;)

traivs: removed android build because it was not finding NDK

---

.travis.yml

Remove the Android build again from TravisCI.
The build failed because the Unity editor was not found. Thus, the other docker image has bigger differences than I had expected.
One would have to fiddle around first with the new docker image to get this working and then migrate all build to them.

travis: removed android build because it was failing

---

UltraStar Play/Assets/Editor/Tests/CompareVersionStringTest.cs
UltraStar Play/Assets/Editor/Tests/CompareVersionStringTest.cs.meta
UltraStar Play/Assets/Editor/Tests/USPlayEditorTests.asmdef
UltraStar Play/Assets/Editor/Tests/USPlayEditorTests.asmdef.meta
UltraStar Play/Assets/Scenes/Main/CompareVersionException.cs
UltraStar Play/Assets/Scenes/Main/CompareVersionException.cs.meta
UltraStar Play/Assets/Scenes/Main/NewVersionChecker.cs
documentation/assembly-dependencies.plantuml

The NewVersionChecker was comparing the numbers of a version string by simply removing all non-digit text.
However, this is not good, because it will consider "1.1.1" smaller than "1.01.01" (because 111 < 10101).
So now
- compare each number separately
- added test for version comparison
- editor tests can now access scene classes via new asmdef file
- removed test assembly from "normal" editor assembly
- updated assembly-dependencies documentation file (plantuml)

fix NewVersionChecker

---

UltraStar Play/Assets/Common/Audio/MidiManager.cs
UltraStar Play/Assets/Common/Model/Setting/SongEditorSettings.cs
UltraStar Play/Assets/Scenes/SongEditor/Actions/ApplyBpmAction.cs
UltraStar Play/Assets/Scenes/SongEditor/Controls/RecordingOptions/SongEditorPlaybackSpeedSlider.cs
UltraStar Play/Assets/Scenes/SongEditor/Controls/SongEditorMusicVolumeSlider.cs
UltraStar Play/Assets/Scenes/SongEditor/Controls/SongEditorMusicVolumeSlider.cs.meta
UltraStar Play/Assets/Scenes/SongEditor/Midi/SongEditorMidiPlaybackOffsetInputField.cs
UltraStar Play/Assets/Scenes/SongEditor/Midi/SongEditorMidiPlaybackOffsetInputField.cs.meta
UltraStar Play/Assets/Scenes/SongEditor/Midi/SongEditorMidiSoundPlayAlong.cs
UltraStar Play/Assets/Scenes/SongEditor/Midi/SongEditorMidiSoundPlayAlongThread.cs
UltraStar Play/Assets/Scenes/SongEditor/Midi/SongEditorMidiSoundPlayAlongThread.cs.meta
UltraStar Play/Assets/Scenes/SongEditor/SongEditorScene.unity

- use separate thread for better accuracy
- configurable offset for MidiPlayAlong
- MidiPlayAlong also works with configured playback speed (e.g. when playing with half the normal tempo)
Besides this:
- added option to regulate music volume for SongEditor
- needed to mix Midi and Music volume
- fixed ApplyBpmAction is not a MonoBehaviour
- there was a warning by Unity, because MonoBehaviour cannot be created using new-keyword
- Before, the MidiPlayAlong was looking in the Update-method which note is currently played. This is not optimal because it will always be at least one frame behind the start of the note and the end of the note. Furthermore, jitter in frames would effect MidiPlayback accuracy
- Now, MidiPlayAlong is much more accurate and can be shifted to eleminate the Midi playback …

SongEditor: better MidiPlayAlong

---

UltraStar Play/Assets/Common/Audio/Recording/MicSampleRecorder.cs
UltraStar Play/Assets/Scenes/Sing/PlayerController/PlayerPitchTracker.cs

Fix PlayerPitchTracker sample rate.
This is a tiny but important PR.
- PlayerPitchTracker first created the analyzer and then initialized the MicSampleRecorder. This way, it was using the default sample rate instead of the correct sample rate for the mic
- I removed the assigned default values. The fields should not be read before the MicProfile has been set.
- Now, the PlayerPitchTracker would just record no notes instead of wrong notes.
- Only the SingScene was affected. Other scenes already initialized the analyzer correctly.
- I noticed that my notes were always just a bit off. Turned out that it was recorded with 48000 Hz but the PlayerPitchTracker used 44100 Hz.
If your mic uses a different sample rate than 44100 or 22050, then you will get much better note recording in the game …

fix: PlayerPitchTracker in SingScene was using wrong sample rate

---

UltraStar Play/Assets/Common/HsvColor/HsvColorMaterial.mat
UltraStar Play/Assets/Scenes/Scenes.asmdef
UltraStar Play/Assets/Scenes/SongSelect/SongSelectScene.unity
UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneController.cs

See title.
**Motivation**
I was confused because the game did not show all of my songs.
So I started debugging.
And then I realized: Damn, I just have a playlist active 🤦 !
(Note that the last used playlist is persisted)
If your own software is confusing you (although correct), then this might be bad UX.
Thus, I guess some hint is required to tell users that the song list is filtered and not showing all songs.
Changing the font of the song-count-label is my approach to this.
The default Unity Text does not support underline style. So I replaced it with one from TextMesh Pro.

SongSelect: indicate active filter via font-style of song-count-label (make it underlined)

---

UltraStar Play/Assets/.gitignore
UltraStar Play/Assets/Common/ApplicationManager.cs
UltraStar Play/Assets/Common/Common.asmdef
UltraStar Play/Assets/Common/Logging.meta
UltraStar Play/Assets/Common/Logging/Log.cs
UltraStar Play/Assets/Common/Logging/Log.cs.meta
UltraStar Play/Assets/Common/Logging/ScalarValueEnricher.cs
UltraStar Play/Assets/Common/Logging/ScalarValueEnricher.cs.meta
UltraStar Play/Assets/Common/Logging/UnityLogEventSink.cs
UltraStar Play/Assets/Common/Logging/UnityLogEventSink.cs.meta
UltraStar Play/Assets/Common/Logging/UnityObjectEnricher.cs
UltraStar Play/Assets/Common/Logging/UnityObjectEnricher.cs.meta
UltraStar Play/Assets/Common/Logging/UnityStackTraceEnricher.cs
UltraStar Play/Assets/Common/Logging/UnityStackTraceEnricher.cs.meta
UltraStar Play/Assets/Plugins/Serilog.meta
UltraStar Play/Assets/Plugins/Serilog/Serilog.asmdef
UltraStar Play/Assets/Plugins/Serilog/Serilog.asmdef.meta
UltraStar Play/Assets/Scenes/Loading/LoadingSceneController.cs
UltraStar Play/Assets/Scenes/Scenes.asmdef
UltraStar Play/ProjectSettings/ProjectSettings.asset
tools/download-dependencies/download-dependencies.sh
tools/download-dependencies/download-serilog.sh

Add Serilog library for logging.
I researched logging libs for C# and found that NLog and Serilog are modern tools for this task.
I tried both. NLog has a big repo (5 MB only the source folder) with everything in it and I got lots of compiler issues.
In contrast, Serilog has a dedicated repo for every sink (i.e. logging target) such that the repos themselves are pretty small (700 KB total for core and file-sink source). I also had only few compiler issues.
Thus I chose Serilog.
- Added define symbol OS_MUTEX for Serilog compilation
- This defines which SharedFileSink implementation is used [OsMutex](https://github.com/serilog/serilog-sinks-file/blob/06e457a3d19b4a0cb00717a0bfd5c3be2d2016fe/src/Serilog.Sinks.File/Sinks/File/SharedFileSink.OSMutex.cs) or …

Serilog for logging

---

.travis.yml

See title.
I already created a Docker account for UltraStar Play and added the credentials to travis.
This PR is only to check that the Travis build succeeds.
#224

travis config: perform docker login before pulling any images

---

UltraStar Play/Assets/Common/Scene/CommonSceneObjects.prefab
UltraStar Play/Assets/Scenes/Highscore/HighscoreScene.unity
UltraStar Play/Assets/Scenes/Highscore/HighscoreSceneInputControl.cs
UltraStar Play/Assets/Scenes/SingingResults/SingingResultsScene.unity
UltraStar Play/Assets/Scenes/SingingResults/SingingResultsSceneInputControl.cs
UltraStar Play/Assets/Scenes/SongSelect/SongSelectFuzzySearchText.cs
UltraStar Play/Assets/Scenes/SongSelect/SongSelectFuzzySearchText.cs.meta
UltraStar Play/Assets/Scenes/SongSelect/SongSelectScene.unity
UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneController.cs
UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneInputControl.cs

This is a small PR.
The "fuzzy search" directly jumps to the song that matches the entered text (in contrast to the normal search, which filters the songs).
New features:
- show the current fuzzy-search-text in the UI
- Extended search if nothing found.
1. search by "title starts with"
2. search by "artist starts with"
3. search by "artist or title contains"

improved fuzzy search in SongSelectScene

---

tools/download-dependencies/download-serilog.sh

there is no master-branch anymore. only dev and main
commit hash stayes the same

Serilog-Dependency correction

---

.github/workflows/build-companion-app.yml
.github/workflows/build-main-game.yml
.github/workflows/test-companion-app.yml
.github/workflows/test-main-game.yml
UltraStar Play/Packages/playshared/Editor/BuildInfoGenerator.cs
UltraStar Play/Packages/playshared/Editor/GitUtils.cs
UltraStar Play/Packages/playshared/Runtime/Util/Extensions/CollectionExtensions.cs

Unity's API returns a wrong value when using `ProjectSettings.bundleVersion`.
The value is now fetched directly from `ProjectSettings.asset` file, which contains the correct value.
Git has some issue such that it does not return the commit hash when running the GitHub Actions build.
The value is now fetched from file `.git/refs/heads/master` without using any Git commands.
Besides this, it also adds `workflow_dispatch` to the GitHub Actions config to start them manually.
close #289
- This annoyance was preventing the new release. Will create a release shortly.

fix BuildInfoGenerator: wrong version number and missing commit hash

---

UltraStar Play/Assets/Common/Model/SettingsManager.cs
UltraStar Play/Assets/Common/R/RMessages.cs
UltraStar Play/Assets/Common/R/RUxmlNames.cs
UltraStar Play/Assets/Scenes/Loading/LoadingSceneControl.cs
UltraStar Play/Assets/Scenes/Options/SongLibraryOptions/SongLibraryOptionsSceneControl.cs
UltraStar Play/Assets/Scenes/Options/SongLibraryOptions/SongLibraryOptionsSceneUi.uxml
UltraStar Play/Packages/playshared/Runtime/Resources/Translations/messages.properties
UltraStar Play/Packages/playshared/Runtime/Resources/Translations/messages_de.properties
UltraStar Play/Packages/playshared/Runtime/Util/AndroidUtils.cs
UltraStar Play/Packages/playshared/Runtime/Util/AndroidUtils.cs.meta

A small PR.
- show path that is required for song folders on Android
- Android does not allow arbitrary access to the files system.
- Notably txt files are only visible to Unity's C# file system API when paths are inside the app specific folder
- The app specific folder can be found using Android's `getExternalFilesDirs`
- I got the initial code to query this from a [blog post](http://anja-haumann.de/unity-how-to-save-on-sd-card/).
- Don't be confused with Android's use of "internal storage" (requires root access), "primary external storage" (app specific storage on internal memory), "secondary external storage" (app specific storage on sd card)
- fun fact: the app specific folder on the internal storage is the what Unity uses as `Application.persistentDataPath`
- added button to add the …

Easier song folder config on Android

---

UltraStar Play/Assets/.gitignore
UltraStar Play/Assets/Common/R/RMessages.cs
UltraStar Play/Assets/Common/R/RUxmlNames.cs
UltraStar Play/Assets/Scenes/About/Texts/License-Overview.txt
UltraStar Play/Assets/Scenes/SongSelect/Search/SongSearchControl.cs
UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneControl.cs
UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneInputControl.cs
UltraStar Play/Assets/Scenes/SongSelect/SongSelectSceneUi.uxml
UltraStar Play/Packages/playshared/Runtime/Resources/Translations/messages.properties
UltraStar Play/Packages/playshared/Runtime/Song/SongMeta.cs
UltraStar Play/Packages/playshared/Runtime/StyleSheets/MainStyles.uss
tools/download-dependencies-main-game/download-dependencies-main-game.sh
tools/download-dependencies-main-game/download-dynamicqueryable.sh
tools/download-dependencies-main-game/download-jokenizer.sh

Enables to filter the song list via C# expressions as discussed in #325 .
- new lib DynamicQueryable (MIT license) is used to filter songs
- new lib Jokenizer.Net (MIT license) is a dependency of DynamicQueryable (from the same author).
- A new overlay shows basic info about the search expressions (see messages.properties)
- Errors in search expressions are shown in UI as icon with tooltip above the search TextField
- Initialized SongMeta strings with empty string instead of null. Otherwise the search expressions can run into a NullPointerException (e.g. when doing `Genre.ToLower().Contains("rock")`)
close #325

search expressions via DynamicQueryable

---

.github/workflows/build-companion-app.yml
.github/workflows/build-main-game.yml
.github/workflows/test-companion-app.yml
.github/workflows/test-main-game.yml
UltraStar Play/Packages/packages-lock.json
UltraStar Play/ProjectSettings/ProjectVersion.txt

Downgrade to Unity 2022.2.1.
Previously an alpha version of Unity (2023.1.0a18) was used, which had other issues.

Anst/unity 2022.2.1

---

UltraStar Play/Packages/playshared/Runtime/Song/UltraStarSongFileWriter.cs

Currently Ultrastar Play song editor saves all song files as UTF-8 with BOM. This happens because in code the encoding is `System.Text.Encoding.UTF8`, which produces a BOM according to [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.text.utf8encoding?view=net-8.0#remarks).
This PR changes the encoding for saved song files to UTF-8 without BOM.
The [Ultrastar format specification](https://usdx.eu/format/) was [recently updated](https://github.com/UltraStar-Deluxe/format/pull/45). It now specifies that all song files should use UTF-8 without BOM as their encoding. There are also tools in the Ultrastar ecosystem, such as Performous Composer, that fail to open song files with BOM.
There is some discussion about UTF-8 BOMs in this Ultrastar format issue …

Change saved song file encoding to UTF-8 without BOM

---

tools/download-dependencies-companion-app/download-compiletimetracker.sh
tools/download-dependencies-companion-app/download-fullserializer.sh
tools/download-dependencies-companion-app/download-leantween.sh
tools/download-dependencies-companion-app/download-serilog.sh
tools/download-dependencies-companion-app/download-sharpziplib.sh
tools/download-dependencies-companion-app/download-unirx.sh
tools/download-dependencies-main-game/download-compiletimetracker.sh
tools/download-dependencies-main-game/download-csharpsynthforunity.sh
tools/download-dependencies-main-game/download-dynamicqueryable.sh
tools/download-dependencies-main-game/download-fullserializer.sh
tools/download-dependencies-main-game/download-jokenizer.sh
tools/download-dependencies-main-game/download-leantween.sh
tools/download-dependencies-main-game/download-serilog.sh
tools/download-dependencies-main-game/download-sharpziplib.sh
tools/download-dependencies-main-game/download-unirx.sh

This PR fixes the currently failing build. It fixes a bug in the dependency download scripts that caused libraries to not be found. See commit message for technical details.
The build was failing. There was a time bomb like behavior in the dependency download scripts where builds could break at any time if a library developer decided to make more than 100 commits after the one that Ultrastar Play depended on. The SharpZipLib dependency failed to download because of this bug.

Fix build failing in dependency setup

---

UltraStar Play/Packages/playshared/Runtime/Song/Builder/SongMetaBuilder.cs

The blank spaces at the end of the lines were a problem. I see that there are several widespread songs like this.
This would make the code more robust.
trimming values for labels
none, but prevented me from opening one because of two problems I found
make the game more robust

Update SongMetaBuilder.cs. trim white spaces 

---

UltraStar Play/Assets/Scenes/SongSelect/Search/SongSearchControl.cs

Change SongSearch to search based on all individual words in the SearchText instead of the literal SearchString
The SongSearch currently searches for the whole string as given. This causes problems and confusions when using to many whitespaces ("ABBA " or "Imagine  Dragons" with two spaces would not find anything) and it makes it difficult to search for artist and title at the same time ("Queen Bohemian" does not find anything). I have seen a lot of people confused about both of these problems.
The more intuitive behaviour would be to split the search string at all whitespaces and to search for each part individually. This small edit should create this behaviour.
One could also add a small button to switch between the two search variants, but I think the proposed variant would almost …

Change SongSearch behaviour
